# Generated by Django 4.0.5 on 2022-07-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteplace',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
