# Generated by Django 4.0.5 on 2022-07-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_favoriteplace_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('user', models.CharField(max_length=200)),
            ],
        ),
    ]
