# Generated by Django 4.0.5 on 2022-07-20 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_storedposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedposts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storedposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
