# Generated by Django 4.0.5 on 2022-07-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_storedposts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedposts',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
