# Generated by Django 4.0.5 on 2022-07-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comments_favoriteplace_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteplace',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
